In [1]:
print("Hello world")

Hello world


## This is my First Program.

In [3]:
import numpy as np

In [9]:
list=[x**2 for x in range(1,11)]
print(list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [10]:
list={x**2 for x in range(1,11)}
print(list)

{64, 1, 4, 36, 100, 9, 16, 49, 81, 25}


In [11]:
list={x:x**2 for x in range(1,11)}
print(list)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [12]:
list=[x**2 for x in range(1,11)]
print(list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [21]:
arr = np.array(list)
print(arr)

[  1   4   9  16  25  36  49  64  81 100]


In [22]:
type(arr)

numpy.ndarray

In [23]:
arr * 2

array([  2,   8,  18,  32,  50,  72,  98, 128, 162, 200])

In [24]:
arr.ndim

1

In [25]:
arr2d=np.array([[1,2,3],[2,4,5],[7,8,9]])

In [26]:
arr2d.ndim

2

In [40]:
li = [
       
           [
           [100,'Samar',10.25],
           [101,'Samary',11.25]
           
                                ],
    
          [
           [1,'Samara',2.25],
           [102,'Samary',1.25]
          
                                
                                   ],
                                    
       
         [
           [100,'Samar',10.25],
           [101,'Samary',11.25]
         ]
                                ,
    
         [ 
           [1,'Samara',2.25],
           [102,'Samary',1.25]
           
                                
                                  ]
                                    ]

In [41]:
arr3d = np.array(li)
print(arr3d)

[[['100' 'Samar' '10.25']
  ['101' 'Samary' '11.25']]

 [['1' 'Samara' '2.25']
  ['102' 'Samary' '1.25']]

 [['100' 'Samar' '10.25']
  ['101' 'Samary' '11.25']]

 [['1' 'Samara' '2.25']
  ['102' 'Samary' '1.25']]]


In [42]:
arr3d.ndim

3

In [47]:
arr3d.shape

(4, 2, 3)

In [46]:
arr3d.size

24

In [45]:
len(arr3d)

4

In [48]:
arr.dtype

dtype('<U21')

In [59]:
list1=[1,2,3,4,5,1.2,1.3]
arr1 = np.array(list1)
print(arr1)

[1.  2.  3.  4.  5.  1.2 1.3]


In [60]:
arr1.dtype

dtype('float64')

In [61]:
arr1.size

7

In [62]:
arr1.itemsize

8

In [63]:
arr = np.array(list)
print(arr)

[  1   4   9  16  25  36  49  64  81 100]


In [65]:
arr.mean()

38.5

In [66]:
arr.min()

1

In [67]:
arr.max()

100

In [69]:
arr.std()

32.41990129534635

In [70]:
arr.var()

1051.05

In [72]:
arr.all()

True

In [76]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
arr1+arr2

array([3, 5, 7])

In [74]:
arr1-arr2

array([-1, -1, -1])

In [87]:
arr3 = np.array([[1,2,3],[3,4,5]])
arr4 = np.array([[1,2],[3,4],[4,5]])
arr3 @ arr4
                 

array([[19, 25],
       [35, 47]])

In [91]:
arr3[arr3<25]

array([1, 2, 3, 3, 4, 5])

In [92]:
arr<25

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [93]:
arr3<25

array([[ True,  True,  True],
       [ True,  True,  True]])

In [94]:
arr4<50

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [99]:
data = np.loadtxt('inp.txt',skiprows=1)
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [100]:
data[0]

array([1., 2., 3.])

In [101]:
data.transpose

<function ndarray.transpose>

In [102]:
data.T

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [105]:
data.T[0].mean()

4.0

In [109]:
data = np.loadtxt('inp.csv',skiprows=1,delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
